### ISSUE TITLE
Non-public album not browseable

### ISSUE THREAD

**Issue by krisavi** [jdriscoll/django-photologue#176]
The public or nonpublic functionality seems to behave a bit not as expected, at least to me. 

With this tickbox I would expect albums to appear in public list when set as public and not appear but still accessible when slug is accessed from address bar. Unfortunately the access to album disappears as well. 

It would be nice to see some more customization there, so you could upload multiple albums and not share them to everyone who access the site, only to specific people, for example those who know the link and then the same with photos section.

**Comment by richardbarran** [comment]
Hi Krisavi,
I think that 'not public' should mean that a gallery/image cannot be accessed _at all_ from the outside - so no direct access via a slug.
That said, there's nothing to stop you [customising this behaviour by overidding the default urls](https://django-photologue.readthedocs.io/en/stable/pages/customising/views.html) and adding your own, so that (for example) you can display all galleries/images, not just the 'public' ones.
